apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fwber-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: fwber.me
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: fwber-backend-service
            port:
              number: 80
      - path: /
        pathType: Prefix
        backend:
          service:
            name: fwber-frontend-service
            port:
              number: 80
