apiVersion: apps/v1
kind: Deployment
metadata:
  name: fwber-redis-replica
  namespace: fwber
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fwber-redis-replica
  template:
    metadata:
      labels:
        app: fwber-redis-replica
    spec:
      containers:
      - name: redis
        image: redis/redis-stack-server:latest
        # Configure as replica of master
        command: ["redis-server", "--replicaof", "fwber-redis-master", "6379"]
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: fwber-redis-replica
  namespace: fwber
spec:
  ports:
  - port: 6379
  selector:
    app: fwber-redis-replica
